//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LearnApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public int Id { get; set; }
        public string nomFormation { get; set; }
        public string nomFormateur { get; set; }
        public string duréeF { get; set; }
        public string certifiée { get; set; }
        public string descriptionF { get; set; }
        public string catégorie { get; set; }
    }
}
